includes:
- ./defaults.yaml

model_config:
  vilt:
    heads:
      masked_coco:
        type: mlm
        freeze: false
        lr_multiplier: 1.0
        # default for bert base
        hidden_size: 768
        # default vocab size for bert base
        vocab_size: 30522

dataset_config:
  masked_coco:
    return_features_info: true
