includes:
- ./defaults.yaml

model_config:
  vilt:
    heads:
      masked_coco:
        type: itm
        freeze: false
        lr_multiplier: 1.0
        # default for bert base
        hidden_size: 768

dataset_config:
  masked_coco:
    return_features_info: true
    false_caption: true
    false_caption_probability: 0.1
