other_configs:
  image_w: 224
  image_h: 224
  hidden_size: 768

dataset_config:
  cmd:
    false_caption: true
    false_caption_probability: 0.1

    images:
      train:
      # COCO
      - coco/defaults/images/trainval2014
      - coco/defaults/images/trainval2014
      # VG Regions
      - /datasets01/VisualGenome1.2/061517/VG_100K_all/
      # CC 12M
      - /large_experiments/cmd/cc12m/images
      # CC 3M
      - /large_experiments/cmd/cc/training
      # SBU Captions
      - /large_experiments/cmd/sbu_captions/images
      # YFCC
      - /large_experiments/cmd/yfcc100m_filtered
      val:
      - coco/defaults/images/trainval2014
      test:
      - coco/defaults/images/trainval2014
    annotations:
      train:
      # COCO
      - /checkpoint/vedanuj/vqa_data/data/imdb/caption/imdb_karpathy_train.npy
      - /checkpoint/vedanuj/vqa_data/data/imdb/caption/imdb_karpathy_restval.npy
      # VG Regions
      - /large_experiments/cmd/visual_genome/vg_region_annotations.npy
      # CC 12M
      - /large_experiments/cmd/cc12m/captions_cleaned.npy
      # CC 3M
      - /large_experiments/cmd/cc/train_all.npy
      # SBU Captions
      - /large_experiments/cmd/sbu_captions/captions.npy
      # YFCC
      - /large_experiments/cmd/yfcc100m_filtered/descriptions.npy
      val:
      - coco/defaults/annotations/imdb_karpathy_val_by_image.npy
      test:
      - coco/defaults/annotations/imdb_karpathy_val_by_image.npy
    processors:
      image_processor:
        type: vilt_image_processor
        params:
          size:
          - ${other_configs.image_w}
          - ${other_configs.image_h}
      text_processor:
        type: vilt_text_tokenizer
        params:
          mask_probability: 0
          max_seq_length: 25

model_config:
  vilt:
    tasks: ${datasets}
    heads:
      cmd:
        type: mlm_itm
        mlm_config:
          freeze: false
          lr_multiplier: 1.0
          vocab_size: 30522
          hidden_size: 768
        itm_config:
          hidden_size: 768
          label_key: is_correct
          freeze: false
          lr_multiplier: 1.0

    losses:
      vqa2: logit_bce

    image_encoder:
      type: vit
      params:
        random_init: True
        pretrained_model_name: google/vit-base-patch16-224
        gradient_checkpointing: false
        do_pooling: false
        hidden_dropout_prob: 0
        add_pooling_layer: False
        do_patch_embeddings: False
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        regularize_bn: False
        regularize_bias: True
        hidden_dim: ${other_configs.hidden_size}
        pretrained_model: vit_base_patch16_224
        mlp_dim: 3072

    image_embeddings:
      type: vilt_img_embedding
      params:
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        hidden_dropout_prob: 0
        hidden_size: ${other_configs.hidden_size}
        patch_size: 16
        num_channels: 3
        random_init: True
        image_encoder: ${model_config.vilt.image_encoder}

    text_embeddings:
      type: vilt_text_embedding
      params:
        bert_model_name: bert-base-uncased
        hidden_dim: ${other_configs.hidden_size}
        hidden_size: 768


training:
  clip_gradients: false
  lr_scheduler: true
  max_updates: 100000
  checkpoint_interval: 4000
  evaluation_interval: 4000
  batch_size: 4096
  find_unused_parameters: false
  num_workers: 1


optimizer:
  type: adam_w_skip_params_with_zero_grad
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 1e-4


scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 4000
    num_training_steps: ${training.max_updates}
